### PR TITLE
Make rspec a development dependency

### PR DESCRIPTION
**Pull request by ababian**
https://thinkneardev.atlassian.net/browse/ES-4252

### CODE REVIEW

**Comment by mxl519** [comment]
wut

**Comment by ababian** [comment]
wat

**Comment by yutamgit** [comment]
the

--

Yuta Morinaga

On Mon, Mar 28, 2016 at 6:11 PM Michael Li

<
mailto:Michael Li <notifications@github.com>
> wrote:

wut

**Comment by mxl519** [comment]
fuck!

**Comment by yutamgit** [comment]
:beers:

**Comment by mxl519** [comment]
Bruh, I'm gonna come Halo Friday, that cool? Make sure to chill the beers in preparation.

@yutamgit You down?

**Comment by yutamgit** [comment]
tempting. Can we start early?

**Comment by mxl519** [comment]
@ababian @preetsethi Still 530 as usual?

**Comment by ababian** [comment]
Yup.

**Comment by eduardog** [comment]
Hi, everyone!

The joys of opensourcing repos. :shipit:

**Comment by preetsethi** [comment]
hello @mxl519 @ababian @eduardog and @yutamgit !

I thought this was about halo RIGHT now

**Comment by brimchan** [comment]
wait... you all still get together for halo?

**Pull request merged**
